const express = require('express');
const path = require('path');

// Importing the code from the Code Examples. Each one is a file in the routes directory
const differentRouteRouter = require('./routes/different-route');

// heroku will assign a port env variable
const PORT = process.env.PORT || 8000;

const app = express()

// Middlewares for using the code from the Code Examples
app.use('/different-route', differentRouteRouter);

// this middleware serves the html files generated by sphinx from the rst files in the sphinx-documentation directory
app.use(express.static(path.join(__dirname, 'public/sphinx-documentation/_build/html')));

app.listen(PORT, () => {
	console.log(`listening on ${PORT}`);
});
